  "body": "{\"erro\": \"Erro SQL ao executar consulta\", \"detalhes\": \"('08001', '[08001] [unixODBC][Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:self signed certificate] (-1) (SQLDriverConnect)')\", \"trace\": \"Traceback (most recent call last):\\n  File \\\"/var/task/lambda_function.py\\\", line 33, in lambda_handler\\n    conn = pyodbc.connect(conn_str)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^\\npyodbc.OperationalError: ('08001', '[08001] [unixODBC][Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:self signed certificate] (-1) (SQLDriverConnect)')\\n\"}"
